
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WingspanFiles.Models.Shared
{
    using Newtonsoft.Json;
    
    public class E974d9e9e5676123cf56d2fd858ece1c24be8be15b96a100963b7cb1afada329
    {

        [JsonProperty("effectiveDate")]
        public string EffectiveDate { get; set; } = default!;

        [JsonProperty("groupNumber")]
        public string GroupNumber { get; set; } = default!;

        [JsonProperty("memberNumber")]
        public string MemberNumber { get; set; } = default!;

        [JsonProperty("status")]
        public E974d9e9e5676123cf56d2fd858ece1c24be8be15b96a100963b7cb1afada329Status Status { get; set; } = default!;
    }
}