
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Benefits.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    
    public enum PlanEnrollmentCoverageMonthFundingStatus
    {
        [JsonProperty("Pending")]
        Pending,
        [JsonProperty("Complete")]
        Complete,
    }

    public static class PlanEnrollmentCoverageMonthFundingStatusExtension
    {
        public static string Value(this PlanEnrollmentCoverageMonthFundingStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static PlanEnrollmentCoverageMonthFundingStatus ToEnum(this string value)
        {
            foreach(var field in typeof(PlanEnrollmentCoverageMonthFundingStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is PlanEnrollmentCoverageMonthFundingStatus)
                    {
                        return (PlanEnrollmentCoverageMonthFundingStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum PlanEnrollmentCoverageMonthFundingStatus");
        }
    }
}