
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SDK.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    
    public enum PlanEnrollmentStatus
    {
        [JsonProperty("Pending")]
        Pending,
        [JsonProperty("Active")]
        Active,
        [JsonProperty("Terminated")]
        Terminated,
    }

    public static class PlanEnrollmentStatusExtension
    {
        public static string Value(this PlanEnrollmentStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static PlanEnrollmentStatus ToEnum(this string value)
        {
            foreach(var field in typeof(PlanEnrollmentStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is PlanEnrollmentStatus)
                    {
                        return (PlanEnrollmentStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum PlanEnrollmentStatus");
        }
    }
}