
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WingspanNotifications.Models.Shared
{
    using Newtonsoft.Json;
    
    public class A71f30be878693b235f8c5f1650be03c9920ca9821526545760476436104c9dc
    {

        [JsonProperty("deductionIds")]
        public object DeductionIds { get; set; } = default!;
    }
}