
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WingspanPayments.Models.Shared
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class UserRoles
    {

        [JsonProperty("ownerIds")]
        public List<string> OwnerIds { get; set; } = default!;

        [JsonProperty("viewerIds")]
        public List<string> ViewerIds { get; set; } = default!;
    }
}