
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WingspanFiles.Models.Operations
{
    using WingspanFiles.Models.Shared;
    using WingspanFiles.Utils;
    
    public class PatchBenefitsServiceIdRequest
    {

        /// <summary>
        /// Unique identifier
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")]
        public string Id { get; set; } = default!;

        [SpeakeasyMetadata("request:mediaType=application/json")]
        public ServiceEnablementUpdate? ServiceEnablementUpdate { get; set; }
    }
}