
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WingspanBookkeeping.Models.Shared
{
    using Newtonsoft.Json;
    using WingspanBookkeeping.Models.Shared;
    
    public class Enrollment
    {

        [JsonProperty("memberId")]
        public string MemberId { get; set; } = default!;

        [JsonProperty("wingspanBenefits")]
        public E974d9e9e5676123cf56d2fd858ece1c24be8be15b96a100963b7cb1afada329 WingspanBenefits { get; set; } = default!;
    }
}