
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace WingspanBookkeeping.Models.Shared
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class PlanEnrollment
    {

        [JsonProperty("coverageMonths")]
        public List<PlanEnrollmentCoverageMonth> CoverageMonths { get; set; } = default!;

        [JsonProperty("createdAt")]
        public string CreatedAt { get; set; } = default!;

        [JsonProperty("currency")]
        public object Currency { get; set; } = default!;

        [JsonProperty("effectiveDate")]
        public string EffectiveDate { get; set; } = default!;

        [JsonProperty("endDate")]
        public string? EndDate { get; set; }

        [JsonProperty("eventActors")]
        public Dictionary<string, string> EventActors { get; set; } = default!;

        [JsonProperty("labels")]
        public Dictionary<string, string> Labels { get; set; } = default!;

        [JsonProperty("memberId")]
        public string MemberId { get; set; } = default!;

        [JsonProperty("monthlyPremium")]
        public double MonthlyPremium { get; set; } = default!;

        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        [JsonProperty("planEnrollmentId")]
        public string PlanEnrollmentId { get; set; } = default!;

        [JsonProperty("planType")]
        public PlanType PlanType { get; set; } = default!;

        [JsonProperty("sku")]
        public string Sku { get; set; } = default!;

        [JsonProperty("status")]
        public Status Status { get; set; } = default!;

        [JsonProperty("updatedAt")]
        public string UpdatedAt { get; set; } = default!;

        [JsonProperty("userRoles")]
        public UserRoles UserRoles { get; set; } = default!;
    }
}